version: '3'

services:
  sleek-airflow:
    image: sleek-airflow:latest

    volumes:
    - ./airflow:/opt/airflow
    # - ./dags:/opt/airflow/dags
    # - ./logs:/opt/airflow/logs
    # - ./plugins:/opt/airflow/plugins

    
    ports:
      - "8080:8080"

    command: airflow standalone